services:
  fyp-db:
    image: postgres:15
    ports:
      - 5436:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: final_year_project_db
    networks:
      - fyp
    volumes:
      - postgres:/var/lib/postgresql/data

  fyp-redis:
    image: redis:latest
    ports:
      - 6377:6379
    networks:
      - fyp
    volumes:
      - redis:/data
    command: [ "redis-server", "--appendonly", "yes" ]

networks:
  fyp:
    name: fyp

volumes:
  postgres:
    name: fyp-postgres-db
  redis:
    name: fyp-redis-data
